engines:
  fixme:
    enabled: true
    config:
          languages:
          - javascript
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
    - "**.js"
exclude_paths:
  - "assets/"