engines:
  fixme:
    enabled: true
    config:
          languages:
          - javascript
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 150
ratings:
  paths:
    - "**.js"
exclude_paths:
  - "assets/"
  - "_src/js/external/"
  - "_src/js/external/modified"
